import type { Theme, ThemeKey, Difficulty, DifficultyConfig } from '../types';

export const STAGE_ORDER: Difficulty[] = ['easy', 'normal', 'hard'];

export const themes: Record<ThemeKey, Theme> = {
  animals: {
    key: 'animals',
    name: '동물',
    icon: '🐾',
    emojis: ['🐶', '🐱', '🐰', '🦊', '🐻', '🐼', '🐸', '🐵', '🦁', '🐯', '🐮', '🐷', '🐔', '🦄', '🐙', '🦋'],
    gradient: 'from-purple-400 to-purple-600',
    gradientFrom: '#a855f7',
    gradientTo: '#9333ea',
  },
  fruits: {
    key: 'fruits',
    name: '과일',
    icon: '🍎',
    emojis: ['🍎', '🍊', '🍋', '🍇', '🍓', '🍑', '🍒', '🥝', '🍌', '🍉', '🫐', '🥭', '🍍', '🥥', '🍈', '🍐'],
    gradient: 'from-green-400 to-green-600',
    gradientFrom: '#4ade80',
    gradientTo: '#16a34a',
  },
  vehicles: {
    key: 'vehicles',
    name: '탈것',
    icon: '🚀',
    emojis: ['🚗', '🚕', '🚁', '🚂', '🚀', '🛸', '🚢', '🏎️', '🚲', '🛵', '🚒', '🚑', '✈️', '🛶', '🚜', '🚠'],
    gradient: 'from-indigo-400 to-indigo-600',
    gradientFrom: '#818cf8',
    gradientTo: '#4f46e5',
  },
  sports: {
    key: 'sports',
    name: '스포츠',
    icon: '⚽',
    emojis: ['⚽', '🏀', '🎾', '⚾', '🏐', '🏈', '🎱', '🏓', '🥊', '🏸', '🏒', '🥋', '🎳', '⛳', '🏹', '🥏'],
    gradient: 'from-blue-400 to-blue-600',
    gradientFrom: '#60a5fa',
    gradientTo: '#2563eb',
  },
  christmas: {
    key: 'christmas',
    name: '크리스마스',
    icon: '🎄',
    emojis: ['🎅', '🎄', '⛄', '🦌', '🎁', '🔔', '❄️', '🕯️', '🧦', '🌟', '🍪', '🤶', '🧣', '🎿', '🛷', '🍬'],
    gradient: 'from-red-400 to-red-600',
    gradientFrom: '#f87171',
    gradientTo: '#dc2626',
  },
  halloween: {
    key: 'halloween',
    name: '할로윈',
    icon: '👻',
    emojis: ['👻', '🎃', '🦇', '🕷️', '🧙‍♀️', '💀', '🕸️', '🧛', '🪦', '🦴', '🍬', '🌙', '🔮', '🧟', '🫧', '☠️'],
    gradient: 'from-orange-500 to-purple-600',
    gradientFrom: '#f97316',
    gradientTo: '#9333ea',
  },
  ocean: {
    key: 'ocean',
    name: '바다',
    icon: '🌊',
    emojis: ['🐠', '🐙', '🦈', '🐋', '🦑', '🐡', '🦀', '🐚', '🪸', '🦞', '🐬', '🦭', '🐟', '🪼', '🦐', '🐳'],
    gradient: 'from-cyan-400 to-blue-600',
    gradientFrom: '#22d3ee',
    gradientTo: '#2563eb',
  },
  music: {
    key: 'music',
    name: '음악',
    icon: '🎵',
    emojis: ['🎸', '🎹', '🥁', '🎺', '🎻', '🪗', '🎷', '🪘', '🎤', '🎵', '🪈', '🎶', '🔔', '🪇', '📯', '🎙️'],
    gradient: 'from-fuchsia-400 to-pink-600',
    gradientFrom: '#e879f9',
    gradientTo: '#db2777',
  },
  dinosaur: {
    key: 'dinosaur',
    name: '공룡',
    icon: '🦕',
    emojis: ['🦕', '🦖', '🌋', '🥚', '🦴', '🪨', '🌿', '🦎', '🐊', '🪹', '🌴', '🐾', '🪺', '🏔️', '🌎', '🔬'],
    gradient: 'from-lime-400 to-green-600',
    gradientFrom: '#a3e635',
    gradientTo: '#16a34a',
  },
  gems: {
    key: 'gems',
    name: '보석',
    icon: '💎',
    emojis: ['💎', '💍', '👑', '🏆', '🔮', '🪩', '✨', '💫', '🌟', '⭐', '🪙', '💰', '🎖️', '🥇', '💠', '🔶'],
    gradient: 'from-violet-400 to-indigo-600',
    gradientFrom: '#a78bfa',
    gradientTo: '#4f46e5',
  },
  fairytale: {
    key: 'fairytale',
    name: '동화',
    icon: '🏰',
    emojis: ['🏰', '👸', '🤴', '🧚', '🦄', '🐉', '🪄', '🧜‍♀️', '👑', '🌈', '🪞', '🧝‍♀️', '🎠', '🦢', '💫', '🍄'],
    gradient: 'from-rose-300 to-purple-500',
    gradientFrom: '#fda4af',
    gradientTo: '#a855f7',
  },
  robot: {
    key: 'robot',
    name: '로봇',
    icon: '🤖',
    emojis: ['🤖', '🔧', '⚙️', '🛠️', '🔩', '💡', '🖥️', '📱', '🎮', '🕹️', '🔌', '💾', '📡', '🛰️', '⌚', '🔋'],
    gradient: 'from-slate-400 to-zinc-600',
    gradientFrom: '#94a3b8',
    gradientTo: '#52525b',
  },
  dessert: {
    key: 'dessert',
    name: '디저트',
    icon: '🧁',
    emojis: ['🧁', '🍰', '🍩', '🍪', '🎂', '🍫', '🍬', '🍭', '🍮', '🧇', '🥞', '🍯', '🧈', '🥐', '🍡', '🍦'],
    gradient: 'from-pink-300 to-rose-500',
    gradientFrom: '#f9a8d4',
    gradientTo: '#f43f5e',
  },
  space: {
    key: 'space',
    name: '우주',
    icon: '🚀',
    emojis: ['🚀', '🌍', '🌙', '⭐', '🛸', '👽', '🪐', '☄️', '🌌', '🔭', '🧑‍🚀', '🛰️', '🌠', '💫', '🌕', '🌑'],
    gradient: 'from-indigo-600 to-violet-900',
    gradientFrom: '#4f46e5',
    gradientTo: '#4c1d95',
  },
  toys: {
    key: 'toys',
    name: '장난감',
    icon: '🧸',
    emojis: ['🧸', '🎲', '🪀', '🪁', '🎯', '🧩', '🎨', '🖍️', '🪆', '🎪', '🤹', '🎠', '🛝', '🪃', '🏀', '🎈'],
    gradient: 'from-red-400 to-yellow-400',
    gradientFrom: '#f87171',
    gradientTo: '#facc15',
  },
  school: {
    key: 'school',
    name: '학교',
    icon: '📚',
    emojis: ['📚', '✏️', '🎒', '📐', '📏', '🔬', '🧪', '🎓', '📝', '🖊️', '📖', '🗺️', '🧮', '📎', '🔔', '🏫'],
    gradient: 'from-emerald-400 to-teal-600',
    gradientFrom: '#34d399',
    gradientTo: '#0d9488',
  },
  summer: {
    key: 'summer',
    name: '여름',
    icon: '🏖️',
    emojis: ['🏖️', '🌴', '🍉', '🕶️', '🩱', '🏄‍♂️', '🧊', '🍧', '🌊', '⛱️', '🦩', '🐚', '🥥', '🌺', '🎆', '🪸'],
    gradient: 'from-sky-400 to-orange-400',
    gradientFrom: '#38bdf8',
    gradientTo: '#fb923c',
  },
  jobs: {
    key: 'jobs',
    name: '직업',
    icon: '🧑‍🚀',
    emojis: ['👨‍🚒', '👩‍⚕️', '👨‍🍳', '👩‍🎤', '👨‍✈️', '👩‍🔬', '👨‍🎨', '👩‍🏫', '👨‍🚀', '👩‍⚖️', '👨‍🌾', '👩‍💻', '🧑‍🔧', '🧑‍🎓', '👷‍♀️', '🦸'],
    gradient: 'from-blue-400 to-indigo-500',
    gradientFrom: '#60a5fa',
    gradientTo: '#6366f1',
  },
  circus: {
    key: 'circus',
    name: '서커스',
    icon: '🎪',
    emojis: ['🎪', '🤡', '🎭', '🤹', '🐘', '🦁', '🎠', '🎈', '🎩', '🪄', '🐒', '🔥', '🎶', '🥁', '🃏', '🌟'],
    gradient: 'from-red-500 to-yellow-500',
    gradientFrom: '#ef4444',
    gradientTo: '#eab308',
  },
  rainbow: {
    key: 'rainbow',
    name: '무지개',
    icon: '🌈',
    emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💗', '💖', '💝', '💕', '🩷', '🩵', '🩶'],
    gradient: 'from-red-400 via-yellow-400 to-blue-400',
    gradientFrom: '#f87171',
    gradientTo: '#60a5fa',
  },
  weather: {
    key: 'weather',
    name: '날씨',
    icon: '🌤️',
    emojis: ['☀️', '🌤️', '⛅', '🌧️', '⛈️', '🌈', '🌪️', '❄️', '🌊', '🌫️', '⛄', '🔥', '🌡️', '💨', '🌙', '🌦️'],
    gradient: 'from-sky-300 to-blue-500',
    gradientFrom: '#7dd3fc',
    gradientTo: '#3b82f6',
  },
  buildings: {
    key: 'buildings',
    name: '건물',
    icon: '🏠',
    emojis: ['🏠', '🏢', '🏰', '🏛️', '🏗️', '⛪', '🕌', '🏟️', '🏥', '🏫', '🏪', '🏭', '🗼', '🗽', '🎪', '🏘️'],
    gradient: 'from-stone-400 to-zinc-600',
    gradientFrom: '#a8a29e',
    gradientTo: '#52525b',
  },
  science: {
    key: 'science',
    name: '과학',
    icon: '🧬',
    emojis: ['🧬', '🔬', '🧪', '⚗️', '🔭', '💊', '🩺', '🧫', '🦠', '💉', '🩻', '🧲', '⚛️', '🔋', '🌡️', '📡'],
    gradient: 'from-emerald-500 to-cyan-500',
    gradientFrom: '#10b981',
    gradientTo: '#06b6d4',
  },
  hands: {
    key: 'hands',
    name: '손동작',
    icon: '✌️',
    emojis: ['👍', '✌️', '🤞', '🤙', '👊', '🫶', '🤝', '👏', '🙌', '🤟', '👋', '🫰', '✋', '🤚', '🖐️', '🤏'],
    gradient: 'from-amber-300 to-orange-400',
    gradientFrom: '#fcd34d',
    gradientTo: '#fb923c',
  },
  zodiac: {
    key: 'zodiac',
    name: '별자리',
    icon: '♈',
    emojis: ['♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '⭐', '🌙', '🔮', '✨'],
    gradient: 'from-violet-500 to-purple-700',
    gradientFrom: '#8b5cf6',
    gradientTo: '#7e22ce',
  },
  family: {
    key: 'family',
    name: '가족',
    icon: '👨‍👩‍👦',
    emojis: ['👶', '👧', '👦', '👩', '👨', '👴', '👵', '🐶', '🐱', '🏠', '🚗', '🌳', '🎄', '💕', '🍳', '📺'],
    gradient: 'from-rose-400 to-pink-500',
    gradientFrom: '#fb7185',
    gradientTo: '#ec4899',
  },
  // API themes
  pokemon: {
    key: 'pokemon',
    name: '포켓몬',
    icon: '🎮',
    emojis: [],
    gradient: 'from-yellow-400 to-red-500',
    gradientFrom: '#facc15',
    gradientTo: '#ef4444',
    isApi: true,
  },
  smileys: {
    key: 'smileys',
    name: '표정',
    icon: '😀',
    emojis: [],
    gradient: 'from-yellow-300 to-orange-400',
    gradientFrom: '#fde047',
    gradientTo: '#fb923c',
    isApi: true,
  },
  flags: {
    key: 'flags',
    name: '국기',
    icon: '🏳️',
    emojis: [],
    gradient: 'from-cyan-400 to-blue-500',
    gradientFrom: '#22d3ee',
    gradientTo: '#3b82f6',
    isApi: true,
  },
  food: {
    key: 'food',
    name: '음식',
    icon: '🍕',
    emojis: [],
    gradient: 'from-amber-400 to-orange-500',
    gradientFrom: '#fbbf24',
    gradientTo: '#f97316',
    isApi: true,
  },
  nature: {
    key: 'nature',
    name: '자연',
    icon: '🌸',
    emojis: [],
    gradient: 'from-pink-400 to-rose-500',
    gradientFrom: '#f472b6',
    gradientTo: '#f43f5e',
    isApi: true,
  },
  dogs: {
    key: 'dogs',
    name: '강아지',
    icon: '🐕',
    emojis: [],
    gradient: 'from-amber-300 to-yellow-500',
    gradientFrom: '#fcd34d',
    gradientTo: '#eab308',
    isApi: true,
  },
  cats: {
    key: 'cats',
    name: '고양이',
    icon: '🐈',
    emojis: [],
    gradient: 'from-orange-300 to-amber-500',
    gradientFrom: '#fdba74',
    gradientTo: '#f59e0b',
    isApi: true,
  },
  digimon: {
    key: 'digimon',
    name: '디지몬',
    icon: '🐲',
    emojis: [],
    gradient: 'from-blue-500 to-cyan-400',
    gradientFrom: '#3b82f6',
    gradientTo: '#22d3ee',
    isApi: true,
  },
  dragonball: {
    key: 'dragonball',
    name: '드래곤볼',
    icon: '🐉',
    emojis: [],
    gradient: 'from-orange-500 to-yellow-400',
    gradientFrom: '#f97316',
    gradientTo: '#facc15',
    isApi: true,
  },
  avatars: {
    key: 'avatars',
    name: '아바타',
    icon: '🎭',
    emojis: [],
    gradient: 'from-teal-400 to-emerald-500',
    gradientFrom: '#2dd4bf',
    gradientTo: '#10b981',
    isApi: true,
  },
  foxes: {
    key: 'foxes',
    name: '여우',
    icon: '🦊',
    emojis: [],
    gradient: 'from-orange-400 to-red-400',
    gradientFrom: '#fb923c',
    gradientTo: '#f87171',
    isApi: true,
  },
  harrypotter: {
    key: 'harrypotter',
    name: '해리포터',
    icon: '🧙',
    emojis: [],
    gradient: 'from-amber-600 to-red-800',
    gradientFrom: '#d97706',
    gradientTo: '#991b1b',
    isApi: true,
  },
  naruto: {
    key: 'naruto',
    name: '나루토',
    icon: '🍥',
    emojis: [],
    gradient: 'from-orange-500 to-amber-600',
    gradientFrom: '#f97316',
    gradientTo: '#d97706',
    isApi: true,
  },
  photos: {
    key: 'photos',
    name: '사진',
    icon: '📷',
    emojis: [],
    gradient: 'from-gray-400 to-slate-600',
    gradientFrom: '#9ca3af',
    gradientTo: '#475569',
    isApi: true,
  },
};

export const difficulties: Record<Difficulty, DifficultyConfig> = {
  easy: { key: 'easy', label: '쉬움', icon: '🐣', cols: 4, rows: 3, pairs: 6 },
  normal: { key: 'normal', label: '보통', icon: '🐥', cols: 4, rows: 4, pairs: 8 },
  hard: { key: 'hard', label: '어려움', icon: '🦅', cols: 5, rows: 4, pairs: 10 },
};

// Grouped by category for display
export const themeGroups: { label: string; icon: string; keys: ThemeKey[] }[] = [
  { label: '동물', icon: '🐾', keys: ['animals', 'ocean', 'dinosaur', 'dogs', 'cats', 'foxes'] },
  { label: '먹거리', icon: '🍽️', keys: ['fruits', 'food', 'dessert'] },
  { label: '캐릭터', icon: '🎮', keys: ['pokemon', 'digimon', 'dragonball', 'harrypotter', 'naruto', 'avatars'] },
  { label: '활동', icon: '⚡', keys: ['sports', 'music', 'school', 'jobs', 'circus', 'hands'] },
  { label: '자연/우주', icon: '🌍', keys: ['nature', 'space', 'summer', 'rainbow', 'weather'] },
  { label: '판타지', icon: '✨', keys: ['fairytale', 'halloween', 'gems', 'zodiac'] },
  { label: '사람/생활', icon: '👨‍👩‍👦', keys: ['family', 'smileys', 'buildings', 'science'] },
  { label: '기타', icon: '🎲', keys: ['vehicles', 'robot', 'toys', 'christmas', 'flags', 'photos'] },
];

export const staticThemeKeys: ThemeKey[] = [
  'animals', 'fruits', 'vehicles', 'sports', 'christmas',
  'halloween', 'ocean', 'music', 'dinosaur', 'gems', 'fairytale', 'robot', 'dessert',
  'space', 'toys', 'school', 'summer', 'jobs', 'circus', 'rainbow',
  'weather', 'buildings', 'science', 'hands', 'zodiac', 'family',
];
export const apiThemeKeys: ThemeKey[] = [
  'pokemon', 'smileys', 'flags', 'food', 'nature', 'dogs',
  'cats', 'digimon', 'dragonball', 'avatars', 'foxes',
  'harrypotter', 'naruto', 'photos',
];
export const themeKeys: ThemeKey[] = [...staticThemeKeys, ...apiThemeKeys];
